/**
 * Hand-authored mock data for the demo build.
 * In production these read from Firestore + the Groq RAG pipeline.
 */

import type {
  Badge,
  BehaviorInsight,
  Challenge,
  LeaderboardEntry,
  Meal,
  Quest,
  User,
  WalkSpot,
} from "./types"

export const currentUser: User = {
  uid: "u_priya_27",
  displayName: "Priya",
  email: "priya@example.com",
  xp: 1280,
  level: 9,
  coins: 240,
  streak: 12,
  steps: 4820,
  stepsTarget: 8000,
  healthGoal: "weight_loss",
  dietaryPreference: "vegetarian",
  cuisinePreference: ["South Indian", "North Indian"],
  preferredLanguage: "en",
  badges: ["streak_3", "streak_7", "meals_10", "voice_first"],
  mealsLogged: 47,
  hydrationGlasses: 5,
  hydrationTarget: 8,
}

export const meals: Meal[] = [
  {
    id: "m_oats_almond",
    meal_name: "Steel-cut oats with almonds & berries",
    image: "/food-oats.jpg",
    calories: 320,
    protein_g: 12,
    carbs_g: 48,
    fat_g: 9,
    fiber_g: 8,
    health_score: 9,
    xp_reward: 45,
    reason:
      "High fiber + slow carbs steady your morning glucose curve and align with your weight-loss goal.",
    preparation_time_min: 8,
    ingredients: ["Steel-cut oats", "Almond milk", "Almonds", "Blueberries", "Cinnamon"],
    tags: ["vegetarian", "high-fiber", "quick"],
    cuisine: "International",
    meal_type: "breakfast",
  },
  {
    id: "m_idli_sambar",
    meal_name: "Idli with sambar & coconut chutney",
    image: "/food-idli.jpg",
    calories: 280,
    protein_g: 10,
    carbs_g: 52,
    fat_g: 4,
    fiber_g: 6,
    health_score: 8,
    xp_reward: 35,
    reason:
      "Fermented, gut-friendly and protein-balanced — a familiar breakfast that supports your goal.",
    preparation_time_min: 12,
    ingredients: ["Idli", "Sambar", "Coconut chutney"],
    tags: ["vegetarian", "south-indian", "comfort"],
    cuisine: "South Indian",
    meal_type: "breakfast",
  },
  {
    id: "m_paneer_bowl",
    meal_name: "Paneer & quinoa power bowl",
    image: "/food-paneer.jpg",
    calories: 460,
    protein_g: 28,
    carbs_g: 42,
    fat_g: 18,
    fiber_g: 7,
    health_score: 9,
    xp_reward: 45,
    reason:
      "Tuesday lunch tends to be protein-light for you. This bowl closes the gap without going heavy.",
    preparation_time_min: 18,
    ingredients: ["Paneer", "Quinoa", "Spinach", "Bell pepper", "Lemon"],
    tags: ["vegetarian", "high-protein", "north-indian"],
    cuisine: "North Indian",
    meal_type: "lunch",
  },
  {
    id: "m_dal_khichdi",
    meal_name: "Moong dal khichdi with curd",
    image: "/food-khichdi.jpg",
    calories: 380,
    protein_g: 16,
    carbs_g: 58,
    fat_g: 7,
    fiber_g: 9,
    health_score: 9,
    xp_reward: 40,
    reason:
      "Stress detected. A calming, low-glycemic comfort meal that keeps your energy stable.",
    preparation_time_min: 20,
    ingredients: ["Moong dal", "Rice", "Ghee", "Cumin", "Curd"],
    tags: ["vegetarian", "comfort", "high-fiber"],
    cuisine: "North Indian",
    meal_type: "dinner",
  },
  {
    id: "m_fruit_yogurt",
    meal_name: "Greek yogurt with seasonal fruit",
    image: "/food-smoothie.jpg",
    calories: 180,
    protein_g: 14,
    carbs_g: 18,
    fat_g: 5,
    fiber_g: 3,
    health_score: 8,
    xp_reward: 25,
    reason:
      "A protein-forward snack that won't crash your afternoon energy.",
    preparation_time_min: 3,
    ingredients: ["Greek yogurt", "Banana", "Honey", "Walnuts"],
    tags: ["vegetarian", "high-protein", "quick"],
    cuisine: "International",
    meal_type: "snack",
  },
]

export const leaderboard: LeaderboardEntry[] = [
  { userId: "u_arjun_20", displayName: "Arjun", xp: 2340, level: 14, streak: 21, rank: 1 },
  { userId: "u_meera_31", displayName: "Meera", xp: 2110, level: 13, streak: 18, rank: 2 },
  { userId: "u_rahul_24", displayName: "Rahul", xp: 1890, level: 12, streak: 9, rank: 3 },
  {
    userId: "u_priya_27",
    displayName: "Priya",
    xp: 1280,
    level: 9,
    streak: 12,
    rank: 4,
    isYou: true,
  },
  { userId: "u_neha_29", displayName: "Neha", xp: 1110, level: 8, streak: 6, rank: 5 },
  { userId: "u_kabir_22", displayName: "Kabir", xp: 980, level: 8, streak: 4, rank: 6 },
  { userId: "u_zoya_26", displayName: "Zoya", xp: 870, level: 7, streak: 11, rank: 7 },
  { userId: "u_dev_25", displayName: "Dev", xp: 720, level: 6, streak: 3, rank: 8 },
]

export const badges: Badge[] = [
  { id: "streak_3", name: "3-Day Warrior", description: "Stay consistent for 3 days", icon: "Flame", unlocked: true },
  { id: "streak_7", name: "Week Champion", description: "7-day streak", icon: "Flame", unlocked: true },
  { id: "streak_30", name: "Iron Habit", description: "30-day streak", icon: "Flame", unlocked: false },
  { id: "meals_10", name: "First Steps", description: "Log 10 meals", icon: "Utensils", unlocked: true },
  { id: "meals_50", name: "Habit Former", description: "Log 50 meals", icon: "Utensils", unlocked: false },
  { id: "xp_500", name: "Rising Star", description: "Earn 500 XP", icon: "Sparkles", unlocked: true },
  { id: "xp_2000", name: "Health Architect", description: "Earn 2000 XP", icon: "Sparkles", unlocked: false },
  { id: "level_10", name: "Double Digits", description: "Reach level 10", icon: "Trophy", unlocked: false },
  { id: "voice_first", name: "Polyglot", description: "First voice interaction", icon: "Mic", unlocked: true },
  { id: "community_win", name: "Mission Complete", description: "Win a group challenge", icon: "Users", unlocked: false },
]

export const challenges: Challenge[] = [
  {
    id: "c_protein_week",
    title: "Protein Architect",
    description: "Hit 60g of protein every day",
    type: "weekly",
    xpReward: 100,
    coinReward: 30,
    progress: 4,
    target: 7,
    isGroupChallenge: false,
  },
  {
    id: "c_hydrate",
    title: "Hydrate Hero",
    description: "Drink 8 glasses of water",
    type: "daily",
    xpReward: 30,
    coinReward: 10,
    progress: 5,
    target: 8,
    isGroupChallenge: false,
  },
  {
    id: "c_neighborhood",
    title: "Bengaluru rises",
    description: "Your city logs 10,000 healthy meals",
    type: "weekly",
    xpReward: 200,
    coinReward: 50,
    progress: 6420,
    target: 10000,
    isGroupChallenge: true,
    participants: 1284,
  },
]

export const insights: BehaviorInsight[] = [
  {
    id: "i_tuesday_protein",
    title: "Tuesday lunches run protein-light",
    body: "On Tuesdays you average 14g of protein at lunch — 40% below your weekday baseline. ARIA queued a 10-minute paneer bowl.",
    severity: "warn",
  },
  {
    id: "i_streak",
    title: "12-day streak — your longest yet",
    body: "You're in the top 8% of users for consistency this month. Variable rewards next.",
    severity: "good",
  },
  {
    id: "i_late_night",
    title: "Late-night snacking down 60%",
    body: "Two weeks ago you ate after 10pm 5x/week. Last week: twice. Sleep quality should follow.",
    severity: "info",
  },
]

/* ---------- New: Quests ---------- */
export const quests: Quest[] = [
  {
    id: "q_protein_lunch",
    title: "Hit 25g protein at lunch",
    description: "ARIA spotted a Tuesday protein dip. Lock it in today.",
    category: "nutrition",
    difficulty: "medium",
    xpReward: 60,
    coinReward: 15,
    progress: 18,
    target: 25,
    status: "active",
    actionLabel: "Log lunch",
  },
  {
    id: "q_hydrate_8",
    title: "Drink 8 glasses of water",
    description: "Steady hydration sharpens your 3pm focus window.",
    category: "hydration",
    difficulty: "easy",
    xpReward: 30,
    coinReward: 10,
    progress: 5,
    target: 8,
    status: "active",
    actionLabel: "Add glass",
  },
  {
    id: "q_walk_8k",
    title: "Walk 8,000 steps",
    description: "Your 14-day average is 6.2k. Push the ceiling once.",
    category: "movement",
    difficulty: "medium",
    xpReward: 80,
    coinReward: 20,
    progress: 4820,
    target: 8000,
    status: "active",
    actionLabel: "Open Explore",
  },
  {
    id: "q_mindful_5",
    title: "5 minutes of mindful breathing",
    description: "Stress detected after 6pm yesterday. Reset tonight.",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 25,
    coinReward: 5,
    progress: 5,
    target: 5,
    status: "ready",
    actionLabel: "Claim XP",
  },
  {
    id: "q_no_late_snack",
    title: "No snacking after 10pm",
    description: "Two weeks ago you broke this 5x. Last week: 2. One more.",
    category: "nutrition",
    difficulty: "hard",
    xpReward: 120,
    coinReward: 30,
    progress: 1,
    target: 1,
    status: "ready",
    actionLabel: "Claim XP",
  },
  {
    id: "q_breakfast_logged",
    title: "Logged a healthy breakfast",
    description: "Steel-cut oats with berries — health score 9/10.",
    category: "nutrition",
    difficulty: "easy",
    xpReward: 45,
    coinReward: 10,
    progress: 1,
    target: 1,
    status: "claimed",
    actionLabel: "Claimed",
  },
]

/* ---------- New: Live Walking spots (stylized map, 0–100 coords) ---------- */
export const walkSpots: WalkSpot[] = [
  {
    id: "w_market",
    name: "Indiranagar farmer's market",
    kind: "market",
    x: 22,
    y: 28,
    distanceM: 320,
    xpReward: 60,
    coinReward: 15,
    blurb: "Stock up on local produce. +5 ingredients this week unlocks a recipe.",
    claimed: false,
  },
  {
    id: "w_jog",
    name: "Cubbon Park jog loop",
    kind: "jog",
    x: 70,
    y: 22,
    distanceM: 540,
    xpReward: 90,
    coinReward: 25,
    blurb: "1.4km loop. Finish under 12 min for a streak bonus.",
    claimed: false,
  },
  {
    id: "w_hydration",
    name: "Public hydration kiosk",
    kind: "hydration",
    x: 38,
    y: 62,
    distanceM: 180,
    xpReward: 25,
    coinReward: 5,
    blurb: "Refill a reusable bottle. Auto-logs +1 glass.",
    claimed: true,
  },
  {
    id: "w_cafe",
    name: "Greens & Grains café",
    kind: "cafe",
    x: 78,
    y: 58,
    distanceM: 410,
    xpReward: 50,
    coinReward: 12,
    blurb: "ARIA-vetted menu. Order any health-9 dish for +30 bonus XP.",
    claimed: false,
  },
  {
    id: "w_yoga",
    name: "Sunrise yoga in the park",
    kind: "yoga",
    x: 55,
    y: 80,
    distanceM: 620,
    xpReward: 70,
    coinReward: 20,
    blurb: "Free 20-min sessions, every weekday at 6:30am.",
    claimed: false,
  },
  {
    id: "w_produce",
    name: "Fresh produce stall",
    kind: "produce",
    x: 14,
    y: 74,
    distanceM: 260,
    xpReward: 40,
    coinReward: 10,
    blurb: "Seasonal fruits. Snap a photo to log a snack instantly.",
    claimed: false,
  },
]
